// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk__KQqStlrbP_NhIiinZYy5gAW5XUQYw',
    appId: '1:759837626024:web:c9019affec2ff951127c9d',
    messagingSenderId: '759837626024',
    projectId: 'my-hand-7dde2',
    authDomain: 'my-hand-7dde2.firebaseapp.com',
    storageBucket: 'my-hand-7dde2.firebasestorage.app',
    measurementId: 'G-68JJN02N8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkvFgUECms07WkW7pvrCpaEfzpbif1-ok',
    appId: '1:759837626024:android:e8218a0fb69ab593127c9d',
    messagingSenderId: '759837626024',
    projectId: 'my-hand-7dde2',
    storageBucket: 'my-hand-7dde2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS5nynDh5kHi7NrYdMUhTa21PGtdPH8Vg',
    appId: '1:759837626024:ios:2dc6a3caa245cbfe127c9d',
    messagingSenderId: '759837626024',
    projectId: 'my-hand-7dde2',
    storageBucket: 'my-hand-7dde2.firebasestorage.app',
    iosBundleId: 'com.example.myHand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS5nynDh5kHi7NrYdMUhTa21PGtdPH8Vg',
    appId: '1:759837626024:ios:2dc6a3caa245cbfe127c9d',
    messagingSenderId: '759837626024',
    projectId: 'my-hand-7dde2',
    storageBucket: 'my-hand-7dde2.firebasestorage.app',
    iosBundleId: 'com.example.myHand',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk__KQqStlrbP_NhIiinZYy5gAW5XUQYw',
    appId: '1:759837626024:web:64e236c7e4decbe0127c9d',
    messagingSenderId: '759837626024',
    projectId: 'my-hand-7dde2',
    authDomain: 'my-hand-7dde2.firebaseapp.com',
    storageBucket: 'my-hand-7dde2.firebasestorage.app',
    measurementId: 'G-9NDHT1SDB4',
  );
}
